### PR TITLE
Remove or refactor workload components with low or no use #61

### PR DESCRIPTION
**Pull request by markus-ntt-seidl**
Remove or refactor workload components with low or no use #61

### CODE REVIEW

**Comment by dubrie** [comment]
@markus-ntt-seidl I think we should combine this with the previous pull request (#140) that is very similar: https://github.com/Green-Software-Foundation/green-software-patterns/pull/140

**Comment by franziska-nttdata-hesselfeld** [comment]
@markus-ntt-seidl @dubrie I would also suggest combining those two pull requests!

**Comment by franziska-nttdata-hesselfeld** [comment]
I merged this PR into #140, so I think we can delete this one.

**Comment by dubrie** [comment]
Closing this pull request as duplicate to #140

**Pull request closed without merging**
