### PR TITLE
52 web does the website avoid tracking user behavior and collecting data unnecessarily

### LINKED ISSUE #52: [Web] Does the website avoid tracking user behavior and collecting data unnecessarily
**Describe the pattern you'd like to propose**
User tracking, user data collection, and targeting in advertisements are responsible for significant energy use in many digital products and services. This is primarily due to the large size of tracking and advertising scripts, the energy required to process and track user behavior, and databases collecting vast amounts of user data. Furthermore, this can present a significant violation of user privacy and tangibly degrade user experience.

**Describe specific emission impact from this pattern**
A clear and concise description of how you see this pattern impacting software emissions.

**References to this pattern**
https://sustainablewebdesign.org/does-the-website-avoid-tracking-user-behaviour-and-collecting-data-unnecessarily/

**Additional context**
Add any other context or screenshots about the proposed pattern here.

### PR DESCRIPTION
**Pull request by dubrie**
Pattern proposal from Issue https://github.com/Green-Software-Foundation/green-software-patterns/issues/52 to avoid collecting tracking data unnecessarily.

### CODE REVIEW

**Comment by dubrie** [comment]
Assigning to @greenhsu123 for initial review

**Review by greenhsu123 — COMMENTED** [review]
Initial review completed! lgtm!

**Comment by dubrie** [comment]
Assigning to @srini1978 for SME Review in Storage category

**Review by srini1978 — APPROVED** [review]
Looks good to me

**Pull request merged**
